#!/bin/sh

res=`ps ax | wc -l`


if [ $res -gt $1 ]; then
    if [ $res -gt $2 ]; then
        echo "CRITICAL. Processes = $res | Processes=$res"
        exit 2
    else
        echo "WARNING. Processes = $res | Processes=$res"
        exit 1
    fi
else
    echo "OK Processes = $res | Processes=$res"
    exit 0
fi
