#!/bin/sh

res=`/usr/sbin/asterisk -r -x "sip show channels" | tail -1 | awk '{print $1}'`

warn_value=$1
crit_value=$2

if [ "`echo "$res >= $warn_value" | bc`" == "1" ]; then
    if [ "`echo "$res >= $crit_value" | bc`" == "1" ]; then
        echo "CRITICAL. sip channels = $res | sip_chan=$res"
        exit 2
    else
        echo "WARNING. sip channels = $res | sip_chan=$res"
        exit 1
    fi
else
    echo "OK sip channels = $res | sip_chan=$res"
    exit 0
fi
