#!/bin/sh

cmd="mysql -u root -vvv "

string1=`hostname`
string2='CTS test work'


function help {
echo -e "\n\tThis plugin check mysql perfomace for INSERT + DELETE operation.\n"
	exit -1
}

# Getting parameters:
while getopts "h:c:w" OPT; do
	case $OPT in
#		"d") disk=$OPTARG;;
		"w") warning=$OPTARG;;
		"c") critical=$OPTARG;;
		"h") help;;
	esac
done

# Doing the actual check:
value=`$cmd -e "INSERT INTO monitor.check_test (test1, test2) VALUES ('$string1','$string2');" | grep "affected" | awk -F "(" '{print $2}' | awk '{print $1}'`
value3=`$cmd -e "SELECT test2 FROM monitor.check_test WHERE test1='$string1';" | grep "row in set" | awk -F "(" '{print $2}' | awk '{print $1}'`
#value3=`$cmd -e "SELECT test2 FROM monitor.check_test WHERE test1='$string1';"`
value2=`$cmd -e "DELETE FROM monitor.check_test WHERE test1='$string1';" | grep "affected" | awk -F "(" '{print $2}' | awk '{print $1}'`
#crit_value=`echo "$value3*0.75" | bc`

#warn_value=`echo "$value3*0.5" | bc`

# Comparing the result and setting the correct level:
#if [ "$value" = "" ]; then
#        msg="CRITICAL"
#        status=2
#else if [ "`echo "$value >= 1000" | bc`" == "1" ]; then
#        	msg="WARNING"
#        	status=1
#     else
        msg="OK"
        status=0
#     fi
#fi

# Printing the results:
echo "$msg - INSERT time = $value, DELETE time = $value2, SELECT time = $value3 | 'instime'=$value; 'deltime'=$value; 'seltime'=$value3;"

# Bye!
exit $status
