#!/bin/sh

month=$(/bin/date +%m)
day=$(/bin/date +%d)
cd /var/lib/mysql

DIRB="/home/backup/mysql"

mkdir -p $DIRB/$month/$day

cd /var/lib/mysql
LIST=`ls -l | grep ^d | awk '{print $9}'`

for basname in $LIST;do 

/usr/bin/mysqldump --add-locks $basname | gzip -9 > $DIRB/${month}/${day}/$basname.gz

done

for month in $(/bin/date -d '3 month ago' +%m) $(/bin/date -d '4 month ago' +%m) $(/bin/date -d '5 month ago' +%m) $(/bin/date -d '6 month ago' +%m);do
    if [ -d $DIRB/$month ]; then
        cd $DIRB/$month && rm -rf *
    fi
done
